#!/usr/bin/env python3

import stat
import os
import sys
from pathlib import Path

def change_mode(path):
    absp = Path(os.path.abspath(path))
    os.chmod(absp, stat.S_IRWXU)

    for p in os.listdir(absp):
        if os.path.isdir(absp / p):
            os.chmod(absp / p, stat.S_IRWXU)
            change_mode(absp / p)

change_mode(sys.argv[1])
